platform :ios, '13.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

# Convert all permission pods into static libraries

target 'videoTest' do
  use_frameworks! :linkage => :static
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'videoTestTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
end
